try {
    hello()
} catch (error) {
    console.log(error);
}

//forma 2 de crear tryCatch
try{
    another()
}catch{
    console.log("hay error");
}